nonlinear_function: softmax
approx_function: vlp
patch_per_layer: True
patched_layer: 18
parameters:
  exp_dim: 8
  window_dim: 16
  window_size: 32
  lut_build: both
  mant_dim: 16
  max_min_exp: {
    1: [1, 'max'],
    2: [-1, 'min'],
    3: [0, 'min'],
    4: [1, 'max'],
    5: [1, 'max'],
    6: [2, 'max'],
    7: [-3, 'min'],
    8: [3, 'max'],
    9: [1, 'max'],
    10: [2, 'max'],
    11: [2, 'max'],
    12: [-4, 'min'],
    13: [2, 'max'],
    14: [2, 'max'],
    15: [2, 'max'],
    16: [2, 'max'],
    17: [2, 'max'],
    min_value: [7, -6, -5, -4, -3, -2, -1, 0, 1], # min
    max_value: [-1, 0, 1, 2, 3, 4, 5, 6, 7], # max
    default: [2, 'max']
  }