nonlinear_function: softmax
approx_function: vlp
# parameters:
#   exp_dim: [8, 9, 10, 11, 12]
#   window_size: 256
#   lut_build: ['max']
#   mant_dim: 8
#   max_min_exp: [-4, -3, -2, -1, 0, 1, 2, 3, 4]
patch_per_layer: True
patched_layer: 16
parameters:
  exp_dim: 8
  window_dim: 8
  window_size: 32
  lut_build: max
  mant_dim: 16
  max_min_exp: {
    1: 1,
    2: 6,
    3: 1,
    4: 3,
    5: 2,
    6: 2,
    7: 1,
    8: 1,
    9: 2,
    10: 2,
    11: 2,
    12: 2,
    13: 2,
    14: 2,
    15: 2,
    # value: [-8, -7, -6, -5], # min
    value: [-1, 0, 1, 2, 3, 4, 5, 6, 7], # max
    default: 2
  }