nonlinear_function: softmax
approx_function: vlp
patch_per_layer: True
patched_layer: 9
parameters:
  exp_dim: 8
  window_dim: 16
  window_size: 32
  lut_build: both
  mant_dim: 16
  max_min_exp: {
    1: [-4, 'min'],
    2: [2, 'max'],
    3: [2, 'max'],
    4: [2, 'max'],
    5: [-4, 'min'],
    6: [3, 'max'],
    7: [2, 'max'],
    8: [3, 'max'],
    min_value: [-5, -4, -3, -2, -1], # min
    max_value: [1, 2, 3, 4, 5], # max
    default: [2, 'max']
  }