nonlinear_function: softmax
approx_function: vlp
patch_per_layer: True
patched_layer: 10
parameters:
  exp_dim: 8
  window_dim: 16
  window_size: 32
  lut_build: both
  mant_dim: 16
  max_min_exp: {
    1: [1, 'max'],
    2: [-1, 'min'],
    3: [1, 'max'],
    4: [-6, 'min'],
    5: [2, 'max'],
    6: [2, 'max'],
    7: [1, 'max'],
    8: [1, 'max'],
    9: [2, 'max'],
    10: [2, 'max'],
    min_value: [-7, -6, -5, -4, -3, -2, -1, 0, 1], # min
    max_value: [-1, 0, 1, 2, 3, 4, 5, 6, 7], # max
    default: [2, 'max']
  }