nonlinear_function: softmax
approx_function: vlp
patch_per_layer: False
parameters:
  exp_dim: 8
  window_dim: 16
  window_size: 32
  lut_build: max
  mant_dim: 16
  # max_min_exp: [-6, -5, -4, -3, -2, -1, 0]
  max_min_exp: [3]