nonlinear_function: softmax
approx_function: vlp
# parameters:
#   exp_dim: [8, 9, 10, 11, 12]
#   window_size: 256
#   lut_build: ['max']
#   mant_dim: 8
#   max_min_exp: [-4, -3, -2, -1, 0, 1, 2, 3, 4]
patch_per_layer: True
patched_layer: 5
parameters:
  exp_dim: 8
  window_dim: 8
  window_size: 32
  lut_build: max
  mant_dim: 16
  max_min_exp: {
    1: 1,
    2: 6,
    3: 1,
    4: 3,
    value: [0, 1, 2, 3, 4, 5, 6, 7, 8],
    default: 2
  }